### PR TITLE
add a function of automatable add KE data-source-table

### PR DESCRIPTION
**Pull request by liuyonghengheng**
add a function that can automatable parse tables from DF.

It supports 4 ways of use：

Mode1: collect the hive table by parsing SQL from sqls parameter 
Mode2: Mode1 + collect the hive table  from DF
Mode3: Mode1 + tables parameter
Mode4: Mode2 + tables parameter

```connect ke where username="ADMIN" 
and password="KYLIN" 
and host="localhost"
and port="7070"
as ff_ke_conn;

set model_sql = '''

select sum(v_revenue) as revenue
from ssb.p_lineorder
left join ssb.dates on lo_orderdate = d_datekey
where d_year = 1993
and lo_discount between 1 and 3
and lo_quantity < 25;select sum(v_revenue) as revenue
from ssb.p_lineorder
left join ssb.dates on lo_orderdate = d_datekey
where d_yearmonthnum = 199401
and lo_discount between 4 and 6
and lo_quantity between 26 and 35

''';

-- -- 支持三种方式 自动添加数据源！

-- -- 第一种方式：
-- -- 解析sqls参数中的sql，从中解析出用到的hive数据源！
-- -- 会解析 sqls 参数中所用到的 所有的hive表，并自动添加到KE数据源。
-- run command as KeAutoModel.`ff_ke_conn.test_ff` where
-- and sqls='''${model_sql}''' and auto_add_tables="true" as newtable1;
-- select * from newtable1 as output;


load hive.`ssb.dates`  as dates;
load hive.`ssb.p_lineorder` as p_lineorder;

select sum(v_revenue) as revenue
from p_lineorder
left join dates on lo_orderdate = d_datekey
where d_year = 1993
and lo_discount between 1 and 3
and lo_quantity < 25  as tmpDF;

-- -- 第二种方式：
-- -- 方式1 + DF 
-- 在做一些探索分析时如果想要把感兴趣的hive sql 使用ke加速，则可以直接使用如下方式。
-- 下面在创建模型是则可以直接自动添加 tmpDF 中用到的数据源（默认不添加）,并且
-- 同时会解析 sqls 参数中所用到的 所有的hive表，并自动添加到KE数据源。
-- 当然也可以使用 方式1 - 不使用tmpDF 而是用command 代替，但是 sqls参数是必须的！
-- 目前只支持 hive表，因为KE目前只支持添加hive数据源。
-- 参数: auto_add_tables 用来控制是否从df中获取数据源并自动添加到KE
run tmpDF as KeAutoModel.`ff_ke_conn.test_ff` where
and sqls='''${model_sql}''' and auto_add_tables="true" as newtable1;
select * from newtable1 as output;
```

-- -- 第三种方式：
-- -- 方式1 + 直接设置数据源tables列表,使用 tables 参数
-- tables 参数：指定ke添加的数据源表名，多个表名使用逗号隔开
run command as KeAutoModel.`ff_ke_conn.test_ff` where
and sqls='''${model_sql}''' 
and auto_add_tables="true"  
and tables="ssb.p_lineorder,ssb.dates" 
as newtable1;
select * from newtable1 as output;
```

### CODE REVIEW

**Comment by fanfanAlice** [comment]
这样用户自动建模就不用担心表没有加载进来啦 点赞

**Comment by allwefantasy** [comment]
I have one question, tmpDF is just used to extract hive tables and help KeAutoModel to load tables,
why not just tell the tables directly E.G:

```
run tmpDF as KeAutoModel.`ff_ke_conn.test_ff` where
and sqls='''${model_sql}''' and auto_add_tables="ssb.dates,ssb.p_lineorder`" as newtable1;
select * from newtable1 as output;
```

**Comment by liuyonghengheng** [comment]
> I have one question, tmpDF is just used to extract hive tables and help KeAutoModel to load tables,
> why not just tell the tables directly E.G:
> 
> ```
> run tmpDF as KeAutoModel.`ff_ke_conn.test_ff` where
> and sqls='''${model_sql}''' and auto_add_tables="ssb.dates,ssb.p_lineorder`" as newtable1;
> select * from newtable1 as output;
> ```

Thank  you WilliamZhu ， I added a new function that can collect the hive table by parsing SQL from sqls parameter

**Comment by fanfanAlice** [comment]
> I have one question, tmpDF is just used to extract hive tables and help KeAutoModel to load tables,
> why not just tell the tables directly E.G:
> 
> ```
> run tmpDF as KeAutoModel.`ff_ke_conn.test_ff` where
> and sqls='''${model_sql}''' and auto_add_tables="ssb.dates,ssb.p_lineorder`" as newtable1;
> select * from newtable1 as output;
> ```
如果sql太多了，那这样手动需要添加的表就太多了，这样用起来会不方便吧

**Comment by liuyonghengheng** [comment]
> > I have one question, tmpDF is just used to extract hive tables and help KeAutoModel to load tables,
> > why not just tell the tables directly E.G:
> > ```
> > run tmpDF as KeAutoModel.`ff_ke_conn.test_ff` where
> > and sqls='''${model_sql}''' and auto_add_tables="ssb.dates,ssb.p_lineorder`" as newtable1;
> > select * from newtable1 as output;
> > ```
> 
> 如果sql太多了，那这样手动需要添加的表就太多了，这样用起来会不方便吧

感谢凡凡提的意见，通过列表的方式我也实现了，用户可以根据需求自由选择

**Comment by liuyonghengheng** [comment]
> I have one question, tmpDF is just used to extract hive tables and help KeAutoModel to load tables,
> why not just tell the tables directly E.G:
> 
> ```
> run tmpDF as KeAutoModel.`ff_ke_conn.test_ff` where
> and sqls='''${model_sql}''' and auto_add_tables="ssb.dates,ssb.p_lineorder`" as newtable1;
> select * from newtable1 as output;
> ```

感谢 William ，你提的建议我也实现了，现在的功能像说明中展示的那样，可以有多重选择方式

**Comment by lwz9103** [comment]
LGTM

**Pull request merged**
